/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.probaescrita_ruibaloterogonzalo;

import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author usuario
 */
public class ProbaEscrita_RuibalOteroGonzalo extends javax.swing.JFrame {

    private DefaultComboBoxModel<String> modeloConcellos;
    private DefaultComboBoxModel<Provincia> modeloProvincias;

    public ProbaEscrita_RuibalOteroGonzalo() {
        initComponents();
        modeloProvincias = new DefaultComboBoxModel<>(provincias);
        modeloConcellos = new DefaultComboBoxModel<>(concellosCorunha);
        cmbLocalidade.setModel(modeloConcellos);
        cmbProvincias.setModel(modeloProvincias);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rbmRestaurantesDisp = new javax.swing.JRadioButtonMenuItem();
        panNovoRestaurante = new javax.swing.JPanel();
        lblCif = new javax.swing.JLabel();
        txtCif = new javax.swing.JTextField();
        lblNome = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        lblPropietario = new javax.swing.JLabel();
        txtPropietario = new javax.swing.JTextField();
        lblEnderezo = new javax.swing.JLabel();
        txtEnderezo = new javax.swing.JTextField();
        lblProvincia = new javax.swing.JLabel();
        cmbProvincias = new javax.swing.JComboBox<>();
        lblLocalidade = new javax.swing.JLabel();
        cmbLocalidade = new javax.swing.JComboBox<>();
        txtGarfos = new javax.swing.JLabel();
        spnGarfos = new javax.swing.JSpinner();
        cbxMenuDia = new javax.swing.JCheckBox();
        btnGardar = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        lblTeléfono = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        lblEspecialidade = new javax.swing.JLabel();
        txtEspecialidade = new javax.swing.JTextField();
        panRestaurantesDisp = new javax.swing.JPanel();
        jrbTodos = new javax.swing.JRadioButton();
        jrbAmosarResMenuDia = new javax.swing.JRadioButton();
        scpRestaurantesDisp = new javax.swing.JScrollPane();
        tblRestaurantesDisp = new javax.swing.JTable();
        btnEliminar = new javax.swing.JButton();

        rbmRestaurantesDisp.setSelected(true);
        rbmRestaurantesDisp.setText("jRadioButtonMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panNovoRestaurante.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Novo restaurante", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("sansserif", 1, 10))); // NOI18N

        lblCif.setText("CIF");

        txtCif.setBackground(java.awt.Color.yellow);

        lblNome.setText("Nome");

        txtNome.setBackground(java.awt.Color.yellow);
        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });

        lblPropietario.setText("Propietario");

        lblEnderezo.setText("Enderezo");

        txtEnderezo.setBackground(java.awt.Color.yellow);
        txtEnderezo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEnderezoActionPerformed(evt);
            }
        });

        lblProvincia.setText("Provincia");

        cmbProvincias.setBackground(java.awt.Color.yellow);
        cmbProvincias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeleccionarProvinciaActionPerformed(evt);
            }
        });

        lblLocalidade.setText("Localidade");

        cmbLocalidade.setBackground(java.awt.Color.yellow);

        txtGarfos.setText("Garfos");

        cbxMenuDia.setText("Menú do día");

        btnGardar.setText("Gardar");
        btnGardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GardarActionPerformed(evt);
            }
        });

        btnLimpar.setText("Limpar");

        lblTeléfono.setText("Telefono");

        txtTelefono.setBackground(java.awt.Color.yellow);

        lblEspecialidade.setText("Especialidade");

        javax.swing.GroupLayout panNovoRestauranteLayout = new javax.swing.GroupLayout(panNovoRestaurante);
        panNovoRestaurante.setLayout(panNovoRestauranteLayout);
        panNovoRestauranteLayout.setHorizontalGroup(
            panNovoRestauranteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panNovoRestauranteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panNovoRestauranteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panNovoRestauranteLayout.createSequentialGroup()
                        .addGroup(panNovoRestauranteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCif)
                            .addComponent(lblEnderezo))
                        .addGap(43, 43, 43)
                        .addComponent(txtCif)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblNome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblPropietario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtPropietario))
                    .addGroup(panNovoRestauranteLayout.createSequentialGroup()
                        .addGroup(panNovoRestauranteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtGarfos)
                            .addComponent(lblTeléfono))
                        .addGap(49, 49, 49)
                        .addGroup(panNovoRestauranteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panNovoRestauranteLayout.createSequentialGroup()
                                .addGroup(panNovoRestauranteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panNovoRestauranteLayout.createSequentialGroup()
                                        .addComponent(txtTelefono, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
                                        .addGap(29, 29, 29)
                                        .addComponent(lblEspecialidade))
                                    .addComponent(txtEnderezo))
                                .addGap(24, 24, 24)
                                .addGroup(panNovoRestauranteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panNovoRestauranteLayout.createSequentialGroup()
                                        .addComponent(lblProvincia)
                                        .addGap(18, 18, 18)
                                        .addComponent(cmbProvincias, 0, 159, Short.MAX_VALUE)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblLocalidade)
                                        .addGap(70, 70, 70)
                                        .addComponent(cmbLocalidade, 0, 158, Short.MAX_VALUE))
                                    .addComponent(txtEspecialidade)))
                            .addGroup(panNovoRestauranteLayout.createSequentialGroup()
                                .addComponent(spnGarfos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbxMenuDia))))
                    .addGroup(panNovoRestauranteLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnGardar)
                        .addGap(43, 43, 43)
                        .addComponent(btnLimpar)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panNovoRestauranteLayout.setVerticalGroup(
            panNovoRestauranteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panNovoRestauranteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panNovoRestauranteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCif)
                    .addComponent(txtCif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNome)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPropietario)
                    .addComponent(txtPropietario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panNovoRestauranteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEnderezo)
                    .addComponent(txtEnderezo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblProvincia)
                    .addComponent(cmbProvincias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLocalidade)
                    .addComponent(cmbLocalidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(panNovoRestauranteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTeléfono)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEspecialidade)
                    .addComponent(txtEspecialidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(panNovoRestauranteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtGarfos)
                    .addComponent(spnGarfos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxMenuDia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panNovoRestauranteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLimpar)
                    .addComponent(btnGardar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panRestaurantesDisp.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Restaurantes disponibles", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("sansserif", 1, 10))); // NOI18N

        jrbTodos.setSelected(true);
        jrbTodos.setText("Amosar todos");

        jrbAmosarResMenuDia.setText("Amosar soamente restaurantes con menú do día");

        tblRestaurantesDisp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Especialidade", "Garfos"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scpRestaurantesDisp.setViewportView(tblRestaurantesDisp);

        btnEliminar.setText("Eliminar restaurante");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panRestaurantesDispLayout = new javax.swing.GroupLayout(panRestaurantesDisp);
        panRestaurantesDisp.setLayout(panRestaurantesDispLayout);
        panRestaurantesDispLayout.setHorizontalGroup(
            panRestaurantesDispLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panRestaurantesDispLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panRestaurantesDispLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scpRestaurantesDisp)
                    .addGroup(panRestaurantesDispLayout.createSequentialGroup()
                        .addComponent(jrbTodos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jrbAmosarResMenuDia)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panRestaurantesDispLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panRestaurantesDispLayout.setVerticalGroup(
            panRestaurantesDispLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panRestaurantesDispLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panRestaurantesDispLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrbTodos)
                    .addComponent(jrbAmosarResMenuDia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scpRestaurantesDisp, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnEliminar)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panRestaurantesDisp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panNovoRestaurante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(6, 6, 6))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panNovoRestaurante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panRestaurantesDisp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtEnderezoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEnderezoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEnderezoActionPerformed

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void SeleccionarProvinciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeleccionarProvinciaActionPerformed
        Provincia p = (Provincia) cmbProvincias.getSelectedItem();

        cargarConcellos(p.getId());
    }//GEN-LAST:event_SeleccionarProvinciaActionPerformed

    private void GardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GardarActionPerformed
        System.out.println(formularioValido());
    }//GEN-LAST:event_GardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProbaEscrita_RuibalOteroGonzalo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProbaEscrita_RuibalOteroGonzalo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProbaEscrita_RuibalOteroGonzalo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProbaEscrita_RuibalOteroGonzalo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProbaEscrita_RuibalOteroGonzalo().setVisible(true);
            }
        });
    }

    private void cargarConcellos(int codProvincia) {
        modeloConcellos.removeAllElements();
        switch (codProvincia) {
            case 1:
                for (int i = 0; i < concellosCorunha.length; i++) {
                    modeloConcellos.addElement(concellosCorunha[i]);
                }
                break;
            case 2:
                for (int i = 0; i < concellosLugo.length; i++) {
                    modeloConcellos.addElement(concellosLugo[i]);
                }
                break;
            case 3:
                for (int i = 0; i < concellosOurense.length; i++) {
                    modeloConcellos.addElement(concellosOurense[i]);
                }
                break;
            case 4:
                for (int i = 0; i < concellosPontevedra.length; i++) {
                    modeloConcellos.addElement(concellosPontevedra[i]);
                }
                break;
        }
    }

    public boolean formularioValido() {

        boolean valido = true;
        String mensaje = "";
//
//        if (!validarCif(txtCif.getText())) {
//            valido = false;
//            mensaje += "";
//        }

        if (!txtNome.getText().matches("([A-Za-z]+\\s*)+")) {
            valido = false;
            mensaje += "";
        }

        if (!txtPropietario.getText().equals("")) {
            if (!txtPropietario.getText().matches("([A-Za-z]+\\s*)+")) {
                valido = false;
                mensaje += "";
            }
        }
        
        // regex para enderezo
        if (!txtEnderezo.getText().matches("")) {
            valido = false;
            mensaje += "";
        }
        
        if (!txtTelefono.getText().matches("[123456789]\\d{8}")) {
            valido = false;
            mensaje += "";
        }

        return valido;

    }
    //Pequena "base de datos" de concellos por provincias
    private String[] concellosCorunha = {"Betanzos", "Ferrol", "Pontedeume"};
    private String[] concellosLugo = {"Foz", "Quiroga", "Triacastela"};
    private String[] concellosOurense = {"Bande", "Castro Caldelas", "Maside"};
    private String[] concellosPontevedra = {"Cangas", "Catoira", "Bueu", "Marín", "Pontevedra", "Tomiño"};
    private Provincia[] provincias = {new Provincia(1, "A Coruña"), new Provincia(2, "Lugo"),
        new Provincia(3, "Ourense"), new Provincia(4, "Pontevedra")
    };


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGardar;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JCheckBox cbxMenuDia;
    private javax.swing.JComboBox<String> cmbLocalidade;
    private javax.swing.JComboBox<Provincia> cmbProvincias;
    private javax.swing.JRadioButton jrbAmosarResMenuDia;
    private javax.swing.JRadioButton jrbTodos;
    private javax.swing.JLabel lblCif;
    private javax.swing.JLabel lblEnderezo;
    private javax.swing.JLabel lblEspecialidade;
    private javax.swing.JLabel lblLocalidade;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblPropietario;
    private javax.swing.JLabel lblProvincia;
    private javax.swing.JLabel lblTeléfono;
    private javax.swing.JPanel panNovoRestaurante;
    private javax.swing.JPanel panRestaurantesDisp;
    private javax.swing.JRadioButtonMenuItem rbmRestaurantesDisp;
    private javax.swing.JScrollPane scpRestaurantesDisp;
    private javax.swing.JSpinner spnGarfos;
    private javax.swing.JTable tblRestaurantesDisp;
    private javax.swing.JTextField txtCif;
    private javax.swing.JTextField txtEnderezo;
    private javax.swing.JTextField txtEspecialidade;
    private javax.swing.JLabel txtGarfos;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtPropietario;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
